version: '3.3'

services:
  app:
    build: .
    image: tina-server
    container_name: tina-server
    ports:
      - '53876:3876'
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    # environment:
    #  - HOST=
    #  - PORT=
    #  - USER=
    #  - PASSWORD=
    # - DATABASE=
    #  - TEST=
